# Generated by Django 4.2.4 on 2023-08-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theatre", "0003_alter_play_options_alter_genre_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="play",
            name="actors",
            field=models.ManyToManyField(related_name="plays", to="theatre.actor"),
        ),
        migrations.AlterField(
            model_name="play",
            name="genres",
            field=models.ManyToManyField(related_name="plays", to="theatre.genre"),
        ),
        migrations.AlterField(
            model_name="play",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
