# Generated by Django 4.2.4 on 2023-08-10 15:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("theatre", "0004_alter_play_actors_alter_play_genres_alter_play_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["row", "seat"]},
        ),
    ]
