# Generated by Django 4.2.4 on 2023-08-10 15:54

from django.db import migrations, models
import theatre.models


class Migration(migrations.Migration):
    dependencies = [
        ("theatre", "0005_alter_ticket_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="play",
            name="image",
            field=models.ImageField(
                null=True, upload_to=theatre.models.movie_image_file_path
            ),
        ),
    ]
